package net.eltown.apiserver.components.handler.groupmanager;

public enum GroupCalls {

    REQUEST_PLAYER_EXISTS,
    REQUEST_GROUP_EXISTS,
    REQUEST_CHECK_FOR_CREATING,
    REQUEST_SET_GROUP,
    REQUEST_ADD_PERMISSION,
    REQUEST_REMOVE_PERMISSION,
    REQUEST_CREATE_GROUP,
    REQUEST_REMOVE_GROUP,
    REQUEST_FULL_GROUP,
    CALLBACK_NULL,
    CALLBACK_SUCCESS,
    CALLBACK_PLAYER_ALREADY_IN_GROUP,
    CALLBACK_PLAYER_DOES_NOT_EXIST,
    CALLBACK_GROUP_PERMISSION_ALREADY_ADDED,
    CALLBACK_GROUP_PERMISSION_NOT_ADDED,
    CALLBACK_GROUP_DOES_NOT_EXIST,
    CALLBACK_GROUP_ALREADY_EXIST,
    CALLBACK_GROUP_EXISTS,
    CALLBACK_FULL_GROUP

}
